"""revert_remove_user_test_note

Revision ID: 64475b724a06
Revises: d56e63a49eb0
Create Date: 2026-02-13 22:43:37.142749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64475b724a06'
down_revision: Union[str, Sequence[str], None] = 'd56e63a49eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_note', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
