"""test_add_user_test_note

Revision ID: d56e63a49eb0
Revises: 3cd8008d8bc5
Create Date: 2026-02-13 22:40:25.896639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56e63a49eb0'
down_revision: Union[str, Sequence[str], None] = '3cd8008d8bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_note')
    # ### end Alembic commands ###
